### ISSUE TITLE
citysdk npm namespace

### ISSUE THREAD

**Issue by loganpowell** [pl12133/pl12133.github.io#1]
Hi Peter,

I'm from the US Census Bureau and am grateful that you took the time to publish an NPM library of our (WIP) citysdk. I was hoping that you could allow us to take ownership of it. Please let me know if you have any questions/concerns.

We intend on releasing a new version (on NPM) very soon. Your soonest convenient response would be very much appreciated.

**Comment by loganpowell** [comment]
Btw, I apologize for communicating with you via your private github repo, but issues aren't enabled on your fork of CitySDK.

**Comment by pl12133** [comment]
:wave: @loganpowell that’s fine to contact me here, I would be happy to turn over ownership of the citysdk package. Is there an email I can contact you at?

**Comment by loganpowell** [comment]
👋 Thank you for your help @pl12133. My email address is logan.t.powell@census.gov
